<?php
require_once __DIR__ . '/middleware/role_check.php';
require_role(['super_admin', 'analyst', 'viewer']);
require_once __DIR__ . '/models/db.php';

function user_can_manage_saved_report(string $reportType): bool
{
    $role = $_SESSION['role'] ?? '';

    if ($role === 'super_admin') {
        return true;
    }

    if ($role !== 'analyst') {
        return false;
    }

    $allowed = $_SESSION['allowed_sections'] ?? '';
    if ($allowed === 'all') {
        return true;
    }

    $sections = array_map('trim', explode(',', $allowed));
    return in_array($reportType, $sections, true);
}

$stmt = $pdo->query("
    SELECT id, report_type, start_date, end_date, generated_by, pdf_path, analyst_comment, created_at
    FROM saved_reports
    ORDER BY created_at DESC
");
$reports = $stmt->fetchAll(PDO::FETCH_ASSOC);

include __DIR__ . '/views/header.php';
include __DIR__ . '/views/navbar.php';
include __DIR__ . '/views/report_styles.php';
?>

<style>
    .manage-section {
        margin-top: 20px;
        padding-top: 20px;
        border-top: 1px solid rgba(255,255,255,0.07);
    }

    .field-label {
        display: block;
        font-size: 0.72rem;
        font-weight: 600;
        text-transform: uppercase;
        letter-spacing: 0.08em;
        color: #9ca3af;
        margin-bottom: 8px;
    }

    .comment-textarea {
        width: 100%;
        min-height: 110px;
        background: rgba(15, 23, 42, 0.72);
        border: 1px solid rgba(255,255,255,0.08);
        border-radius: 10px;
        color: #e5e7eb;
        padding: 12px 14px;
        font: inherit;
        line-height: 1.55;
        resize: vertical;
        outline: none;
        box-sizing: border-box;
        transition: border-color 150ms ease, box-shadow 150ms ease, background 150ms ease;
        margin-bottom: 12px;
    }

    .comment-textarea:focus {
        border-color: rgba(79,124,255,0.7);
        box-shadow: 0 0 0 3px rgba(79,124,255,0.16);
        background: rgba(15, 23, 42, 0.9);
    }

    .comment-textarea::placeholder {
        color: #6b7280;
    }

    .manage-actions {
        display: flex;
        align-items: center;
        gap: 10px;
        flex-wrap: wrap;
        margin-top: 12px;
    }

    .inline-form {
        margin: 0;
    }

    .btn-update {
        background: #4f7cff;
        border: none;
        border-radius: 9px;
        color: #fff;
        padding: 9px 20px;
        font-family: 'DM Sans', sans-serif;
        font-size: 0.85rem;
        font-weight: 500;
        cursor: pointer;
        transition: background 150ms ease, box-shadow 150ms ease, transform 100ms ease;
    }

    .btn-update:hover {
        background: #6b93ff;
        box-shadow: 0 0 18px rgba(79,124,255,0.35);
    }

    .btn-update:active {
        transform: translateY(1px);
    }

    .btn-delete {
        background: transparent;
        border: 1px solid rgba(248,113,113,0.35);
        border-radius: 9px;
        color: #f87171;
        padding: 9px 20px;
        font-family: 'DM Sans', sans-serif;
        font-size: 0.85rem;
        font-weight: 500;
        cursor: pointer;
        transition: background 150ms ease, border-color 150ms ease, transform 100ms ease;
    }

    .btn-delete:hover {
        background: rgba(248,113,113,0.1);
        border-color: #f87171;
    }

    .btn-delete:active {
        transform: translateY(1px);
    }
</style>

<div class="report-page">
    <h1>Saved Reports</h1>
    <p class="subtitle">Previously generated report snapshots.</p>

    <?php if (empty($reports)): ?>
        <div class="notes-card">
            <p>No saved reports yet.</p>
        </div>
    <?php else: ?>
        <?php foreach ($reports as $report): ?>
            <?php $canManage = user_can_manage_saved_report((string)$report['report_type']); ?>

            <div class="notes-card">
                <h2><?php echo htmlspecialchars(ucfirst($report['report_type']) . ' Snapshot', ENT_QUOTES, 'UTF-8'); ?></h2>

                <p>
                    <strong>Date Range:</strong>
                    <?php echo htmlspecialchars($report['start_date'], ENT_QUOTES, 'UTF-8'); ?>
                    →
                    <?php echo htmlspecialchars($report['end_date'], ENT_QUOTES, 'UTF-8'); ?>
                </p>

                <p>
                    <strong>Generated By:</strong>
                    <?php echo htmlspecialchars($report['generated_by'], ENT_QUOTES, 'UTF-8'); ?>
                </p>

                <p>
                    <strong>Created At:</strong>
                    <?php echo htmlspecialchars($report['created_at'], ENT_QUOTES, 'UTF-8'); ?>
                </p>

                <?php
                $pdfPath = $report['pdf_path'] ?? '';
                $fullPdfPath = __DIR__ . $pdfPath;
                ?>

                <p>
                    <?php if ($pdfPath !== '' && file_exists($fullPdfPath)): ?>
                        <a href="<?php echo htmlspecialchars($pdfPath, ENT_QUOTES, 'UTF-8'); ?>" target="_blank">Open Saved PDF</a>
                    <?php else: ?>
                        <span style="color:#999;">Report file missing</span>
                    <?php endif; ?>
                </p>

                <div class="insight-box">
                    <strong>Analyst Comment</strong>
                    <?php if (!empty($report['analyst_comment'])): ?>
                        <p style="margin-top:8px;">
                            <?php echo nl2br(htmlspecialchars($report['analyst_comment'], ENT_QUOTES, 'UTF-8')); ?>
                        </p>
                    <?php else: ?>
                        <p style="margin-top:8px;"><em>No analyst comment added.</em></p>
                    <?php endif; ?>
                </div>

                <?php if ($canManage): ?>
                    <div class="manage-section">
                        <label class="field-label" for="comment_<?php echo (int)$report['id']; ?>">
                            Edit Comment
                        </label>

                        <form method="POST" action="/update_saved_report_comment.php">
                            <input type="hidden" name="report_id" value="<?php echo htmlspecialchars((string)$report['id'], ENT_QUOTES, 'UTF-8'); ?>">

                            <textarea
                                id="comment_<?php echo (int)$report['id']; ?>"
                                name="analyst_comment"
                                rows="4"
                                class="comment-textarea"
                            ><?php echo htmlspecialchars($report['analyst_comment'] ?? '', ENT_QUOTES, 'UTF-8'); ?></textarea>

                            <div class="manage-actions">
                                <button type="submit" class="btn-update">Update Comment</button>
                        </form>

                                <form
                                    method="POST"
                                    action="/delete_saved_report.php"
                                    class="inline-form"
                                    onsubmit="return confirm('Delete this saved report? This will also remove the PDF file.');"
                                >
                                    <input type="hidden" name="report_id" value="<?php echo htmlspecialchars((string)$report['id'], ENT_QUOTES, 'UTF-8'); ?>">
                                    <button type="submit" class="btn-delete">Delete Report</button>
                                </form>
                            </div>
                    </div>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
</div>

<?php include __DIR__ . '/views/footer.php'; ?>
